# Generated by Django 5.0.6 on 2024-05-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_register_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='default@example.com', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='your_default_email@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
