# Generated by Django 5.0.6 on 2024-05-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_register_confirmpassword_register_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
