# Generated by Django 5.0.6 on 2024-05-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='emails',
        ),
    ]
