# Generated by Django 5.0.6 on 2024-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goLL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbb', models.CharField(max_length=44)),
                ('bbba', models.TextField(max_length=55)),
                ('dbdd', models.TextField(max_length=23)),
            ],
        ),
    ]
