# Generated by Django 5.0.6 on 2024-05-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=285, null=True)),
                ('emails', models.EmailField(max_length=254, unique=True)),
                ('passwords', models.CharField(max_length=215)),
                ('roles', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='goLL',
        ),
    ]
