# Generated by Django 5.0.6 on 2024-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_register_confirmpassword_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirmpassword',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
