# Generated by Django 5.0.6 on 2024-05-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
