# Generated by Django 5.0.6 on 2024-05-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
    ]
