# Generated by Django 5.0.6 on 2024-05-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_register_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirmpassword',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
