# Generated by Django 5.0.6 on 2024-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=15, null=True)),
                ('province', models.TextField(blank=True, max_length=50, null=True)),
                ('district', models.TextField(blank=True, max_length=50, null=True)),
                ('tabun', models.TextField(blank=True, max_length=50, null=True)),
                ('detel', models.TextField(blank=True, max_length=50, null=True)),
                ('postcode', models.IntegerField(blank=True, max_length=10, null=True)),
                ('road', models.TextField(blank=True, max_length=50, null=True)),
                ('village', models.IntegerField(blank=True, max_length=80, null=True)),
                ('other', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
